# Generated by Django 6.1.1 on 2026-10-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=20)),
                ('nroDocumento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('fechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomicacion', models.CharField(max_length=100)),
                ('pesoMinMacho', models.FloatField()),
                ('pesoMaxMacho', models.FloatField()),
                ('alturaMediaMacho', models.FloatField()),
                ('pesoMinHembra', models.FloatField()),
                ('pesoMaxHembra', models.FloatField()),
                ('alturaMediaHembra', models.FloatField()),
                ('cuidadosEspeciales', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mi_app.empleado')),
                ('legajo', models.CharField(max_length=20)),
            ],
            bases=('mi_app.empleado',),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mi_app.empleado')),
                ('matriculaHabilitante', models.CharField(max_length=20)),
            ],
            bases=('mi_app.empleado',),
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroHistoriaClinica', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.empleado')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.raza')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.sucursal')),
            ],
        ),
    ]
