# Generated by Django 6.1.1 on 2026-10-05 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabueso_feliz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaProgramada', models.DateField()),
                ('fechaAplicacion', models.DateField(blank=True, null=True)),
                ('laboratorio', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroOrden', models.CharField(max_length=20)),
                ('fechaEntrada', models.DateField()),
                ('internado', models.BooleanField()),
                ('fechaSalida', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('periodisidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaUltimaCompra', models.DateField()),
                ('cantidadExistente', models.IntegerField()),
                ('cantidadMinima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='altura',
            new_name='alturaActual',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='peso',
            new_name='pesoActual',
        ),
        migrations.AlterField(
            model_name='perro',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.duenio'),
        ),
    ]
