# Generated by Django 6.1.1 on 2026-10-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabueso_feliz', '0002_calendariovacuna_consulta_diagnostico_duenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='empleado_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sabueso_feliz.empleado'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.duenio'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.raza'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.sucursal'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='empleado_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sabueso_feliz.empleado'),
        ),
    ]
